// =============================================================================
// 78枚のタロットカード完全定義
// 大アルカナ22枚 + 小アルカナ56枚（杖・聖杯・剣・金貨 各14枚）
// numericId は 0〜77（v2.0 交換機能のレア度計算に使用）
// =============================================================================

export type Suit = 'major' | 'wands' | 'cups' | 'swords' | 'pentacles'
// レア度（4 段階）。tarot-data 側は static な source of truth。
// 漢字表記とアニメ振り分けは lib/card-rarity.ts:CardRarity と一致させる。
//   common    (40) → 常：小アルカナ数札 1〜10
//   epic      (16) → 貴：小アルカナコート 11〜14
//   rare      (14) → 稀：大アルカナのうち legendary 以外
//   legendary  (8) → 極：大アルカナの 0/10/13/16/17/18/19/21
export type Rarity = 'common' | 'rare' | 'epic' | 'legendary'

export type TarotCard = {
  id: string
  numericId: number
  name: string
  nameEn: string
  suit: Suit
  number: number
  keywords: string[]
  meaningUpright: string
  meaningReversed: string
  rarity: Rarity
}

export const TAROT_CARDS: readonly TarotCard[] = [
  // === 大アルカナ 0〜10（rare：11枚）===
  {
    id: 'major-00',
    numericId: 0,
    name: '愚者',
    nameEn: 'The Fool',
    suit: 'major',
    number: 0,
    keywords: ['出発', '無垢', '可能性'],
    meaningUpright: '白紙の心で旅に出る朝。崖の縁にも風は通い、見えぬ道を月光が照らす。恐れを脱ぎ捨て、軽やかに一歩を踏み出せば、新たな縁が静かに開く。',
    meaningReversed: '焦りが足取りを乱す時。心の支度なき出立は迷い路を呼ぶ。立ち止まり、足元の灯を確かめてから、再び歩み始めても遅くはない。',
    rarity: 'legendary',
  },
  {
    id: 'major-01',
    numericId: 1,
    name: '魔術師',
    nameEn: 'The Magician',
    suit: 'major',
    number: 1,
    keywords: ['創造', '意志', '顕現'],
    meaningUpright: '手の中に星と土を握る時。天地の力をひとつに紡ぎ、想いを形へと変える術がある。澄んだ意志を筆に乗せれば、世界はあなたに応える。',
    meaningReversed: '技を弄び、目的を見失う恐れ。器は揃えど、心が定まらねば言葉は風に散る。一度静まり、初心の灯を確かめてから動こう。',
    rarity: 'rare',
  },
  {
    id: 'major-02',
    numericId: 2,
    name: '女教皇',
    nameEn: 'The High Priestess',
    suit: 'major',
    number: 2,
    keywords: ['直感', '静寂', '内なる声'],
    meaningUpright: '月光の差す回廊で耳を澄ます時。語らずとも知る心の声があり、答えはすでに胸の奥に在る。急がず、静けさの中で真実を聴き取ろう。',
    meaningReversed: '内なる声を雑音が覆う時。表層の言葉に揺さぶられず、独りの静謐へ戻ろう。直感は鎮まる水面にこそ姿を映し出す。',
    rarity: 'rare',
  },
  {
    id: 'major-03',
    numericId: 3,
    name: '女帝',
    nameEn: 'The Empress',
    suit: 'major',
    number: 3,
    keywords: ['豊穣', '母性', '創造'],
    meaningUpright: '大地が花を抱くごとく、豊かさが手の中に満ちる時。慈しみと美しさで人を包み、創造の種に水を注ごう。すべては実りへ向かう。',
    meaningReversed: '与えすぎて己が枯れぬよう。母なる役を装い疲れる前に、自らに春を許そう。自身の田畑にも、優しき雨を降らせて。',
    rarity: 'rare',
  },
  {
    id: 'major-04',
    numericId: 4,
    name: '皇帝',
    nameEn: 'The Emperor',
    suit: 'major',
    number: 4,
    keywords: ['秩序', '意志', '統べる'],
    meaningUpright: '揺るがぬ柱を立てる時。秩序と理を以て道を切り拓き、領土を守る盾となる。冷静な意志こそが、混迷を晴らす光である。',
    meaningReversed: '力に頼りすぎ、心が固くなる時。鎧の下の柔らかさを忘れずに。支配ではなく、信に基づく統べを取り戻そう。',
    rarity: 'rare',
  },
  {
    id: 'major-05',
    numericId: 5,
    name: '教皇',
    nameEn: 'The Hierophant',
    suit: 'major',
    number: 5,
    keywords: ['伝統', '導き', '信仰'],
    meaningUpright: '古き道の中に智慧の灯がある。先達の言葉に耳を傾け、敬いを以て学ぶ時。形を踏むことが、心の自由へとつながってゆく。',
    meaningReversed: '形骸に縛られぬよう注意。教えの皮ではなく芯を問い直し、己の信仰を新しく結び直そう。型破りもまた、敬いの一つの姿。',
    rarity: 'rare',
  },
  {
    id: 'major-06',
    numericId: 6,
    name: '恋人',
    nameEn: 'The Lovers',
    suit: 'major',
    number: 6,
    keywords: ['結び', '選択', '共鳴'],
    meaningUpright: '二つの心が共に響く時。選びの前に立つあなたに、天の鳥居が祝福を授ける。誠の声に従えば、その縁は深く長く続いてゆく。',
    meaningReversed: '心が二つに割れる時。世間の声に流されず、自分が真に欲するものを見定めよう。曖昧な約束は、後の歪みを生む。',
    rarity: 'rare',
  },
  {
    id: 'major-07',
    numericId: 7,
    name: '戦車',
    nameEn: 'The Chariot',
    suit: 'major',
    number: 7,
    keywords: ['前進', '意志', '制御'],
    meaningUpright: '二頭の馬を御す手綱を握る時。相反する力を統べ、まっすぐに前進する勝利の道。意志を一本に通せば、城門も自ずと開く。',
    meaningReversed: '御し方を誤れば、車は横へ逸れる。焦りや怒りに任せた前進は痛手を呼ぶ。一度馬を休め、方角を見直してから走ろう。',
    rarity: 'rare',
  },
  {
    id: 'major-08',
    numericId: 8,
    name: '力',
    nameEn: 'Strength',
    suit: 'major',
    number: 8,
    keywords: ['優しさ', '勇気', '内なる獅子'],
    meaningUpright: '真の強さは静けさに宿る。猛き獅子の鬣をそっと撫でるごとく、優しき手で己を制す時。柔らかさこそが、最も折れぬ刃となる。',
    meaningReversed: '内なる獣に翻弄される時。怒りや欲を押し殺さず、まず認めて寄り添おう。力の発露は、自己への慈しみから始まる。',
    rarity: 'rare',
  },
  {
    id: 'major-09',
    numericId: 9,
    name: '隠者',
    nameEn: 'The Hermit',
    suit: 'major',
    number: 9,
    keywords: ['内省', '静謐', '灯'],
    meaningUpright: 'ひとり山道を行く時。手にする提灯は遠くを照らさずとも、足元を確かに照らす。孤独の中でしか聴こえぬ声が、あなたを導いてゆく。',
    meaningReversed: '籠もりすぎて世から離れすぎぬよう。内なる声を得たならば、いつかは里へ降り、灯を他者にも分けてゆく時が来る。',
    rarity: 'rare',
  },
  {
    id: 'major-10',
    numericId: 10,
    name: '運命の輪',
    nameEn: 'Wheel of Fortune',
    suit: 'major',
    number: 10,
    keywords: ['巡り', '転機', '流れ'],
    meaningUpright: '大きな車輪が廻り出す時。逆らわず、流れに身を委ねれば、思いがけぬ追い風が背を押す。今この瞬間こそ、運命の節目である。',
    meaningReversed: '輪の停滞、あるいは逆回りの時。抗えば泥を被るのみ。今は嵐の通り過ぎるを待ち、新たな波の兆しに目を凝らそう。',
    rarity: 'legendary',
  },

  // === 大アルカナ 11〜21（legendary：11枚）===
  {
    id: 'major-11',
    numericId: 11,
    name: '正義',
    nameEn: 'Justice',
    suit: 'major',
    number: 11,
    keywords: ['公正', '真実', '釣り合い'],
    meaningUpright: '天秤が静かに釣り合う時。情に流されず、事の道理を見つめる目を持とう。公正な選択は、後の世にまで澄んだ風を残してゆく。',
    meaningReversed: '偏った秤に注意。私情や偏見が判断を曇らせている。一度天秤を空にし、改めて事実だけを乗せ直してみよう。',
    rarity: 'rare',
  },
  {
    id: 'major-12',
    numericId: 12,
    name: '吊るされた男',
    nameEn: 'The Hanged Man',
    suit: 'major',
    number: 12,
    keywords: ['受容', '視点転換', '静止'],
    meaningUpright: '逆さまの世から景色を眺める時。動かぬことが最大の動きとなる。手放した先にこそ、新しき答えが頭上から舞い降りてくる。',
    meaningReversed: '犠牲ばかりが嵩む時。耐えるだけが智慧ではない。縄を解き、地に足を戻して、別の角度から事を見つめ直そう。',
    rarity: 'rare',
  },
  {
    id: 'major-13',
    numericId: 13,
    name: '死神',
    nameEn: 'Death',
    suit: 'major',
    number: 13,
    keywords: ['終焉', '変容', '再生'],
    meaningUpright: '落葉が地に還る秋の朝。一つの章を閉じる時、悲しみは肥やしへ変わる。古き衣を脱ぎ、生まれ変わる魂の入口に立っている。',
    meaningReversed: '終わらせるべきを終わらせられぬ時。執着は腐葉となる。手放しの怖さを認めつつ、ひと枝だけでも剪定してみよう。',
    rarity: 'legendary',
  },
  {
    id: 'major-14',
    numericId: 14,
    name: '節制',
    nameEn: 'Temperance',
    suit: 'major',
    number: 14,
    keywords: ['調和', '中庸', '注ぎ'],
    meaningUpright: '二つの杯の間を清らかな水が行き交う時。火と水、急ぐ心と待つ心、その均衡こそが妙なる調べを生む。穏やかな歩みを大切に。',
    meaningReversed: '釣り合いを欠き、何かが溢れる時。極端へ振れた心を中心へ戻そう。少しずつ、ゆっくりと、湯を冷ますように。',
    rarity: 'rare',
  },
  {
    id: 'major-15',
    numericId: 15,
    name: '悪魔',
    nameEn: 'The Devil',
    suit: 'major',
    number: 15,
    keywords: ['束縛', '欲', '影'],
    meaningUpright: '自ら結んだ鎖に気づく時。鍵はずっと自分の手の中にある。欲や恐れの影を直視し、笑い飛ばせば、縛めは音を立てて崩れる。',
    meaningReversed: '鎖が緩み始める兆し。長く依ったものから一歩離れ、軽くなる自分を許そう。解放は、ささやかな選び直しから始まる。',
    rarity: 'rare',
  },
  {
    id: 'major-16',
    numericId: 16,
    name: '塔',
    nameEn: 'The Tower',
    suit: 'major',
    number: 16,
    keywords: ['崩壊', '啓示', '解放'],
    meaningUpright: '雷が古き楼を打ち砕く時。痛みの後には澄み渡った空が残る。偽りの土台を恐れず手放せば、本物の地盤が顕れてくる。',
    meaningReversed: '崩落をかろうじて避けた時。ひびに気づき始めた今こそ、補修ではなく建て直しの選択を。先延ばしは更なる損を呼ぶ。',
    rarity: 'legendary',
  },
  {
    id: 'major-17',
    numericId: 17,
    name: '星',
    nameEn: 'The Star',
    suit: 'major',
    number: 17,
    keywords: ['希望', '浄化', '静かな祈り'],
    meaningUpright: '夜空にひと粒の星が瞬く時。傷ついた心に冷水が注がれ、再び信じる力が芽吹いてゆく。願いは静かに、しかし確かに叶ってゆく。',
    meaningReversed: '希望の星が雲に隠れる時。理想が遠く感じても、灯は消えてはいない。今は俯きを許し、ゆっくりと顔を上げてゆこう。',
    rarity: 'legendary',
  },
  {
    id: 'major-18',
    numericId: 18,
    name: '月',
    nameEn: 'The Moon',
    suit: 'major',
    number: 18,
    keywords: ['幻', '不安', '直感の試み'],
    meaningUpright: '月光の道に犬と狼が吠える時。見えるものと見えぬものの境で揺らぐ心。不安を友とし、夢の声に耳を澄ませば道は現れる。',
    meaningReversed: '霧が晴れ始める時。長く見えなかった真実が、薄明に姿を見せる。怖れていたものの正体に、案外驚かされぬかもしれない。',
    rarity: 'legendary',
  },
  {
    id: 'major-19',
    numericId: 19,
    name: '太陽',
    nameEn: 'The Sun',
    suit: 'major',
    number: 19,
    keywords: ['喜び', '顕現', '祝福'],
    meaningUpright: '真昼の陽が万物を照らす時。隠していた本来の光を惜しまず放とう。子どものごとき笑みが、周囲の景色までも金色に染め変える。',
    meaningReversed: '雲が陽を遮る時。喜びを取り繕う必要はない。一度光を内に仕舞い、本当の幸福の在処を静かに探し直してみよう。',
    rarity: 'legendary',
  },
  {
    id: 'major-20',
    numericId: 20,
    name: '審判',
    nameEn: 'Judgement',
    suit: 'major',
    number: 20,
    keywords: ['覚醒', '召命', '赦し'],
    meaningUpright: '遠くから法螺貝の音が響く時。過去のすべてを抱いたまま、新たな使命の名を呼ばれている。立ち上がり、自らを赦して進もう。',
    meaningReversed: '呼び声が耳に届かぬ時。過去への悔いが扉を塞いでいる。許せぬ何かに先に手向け、心の喪を終えてから歩み出そう。',
    rarity: 'rare',
  },
  {
    id: 'major-21',
    numericId: 21,
    name: '世界',
    nameEn: 'The World',
    suit: 'major',
    number: 21,
    keywords: ['完成', '統合', '円環'],
    meaningUpright: '円が静かに閉じる時。長き旅の終わりに、すべての要素が一つに結ばれる。達成の喜びを噛みしめ、次なる円の中心へ歩もう。',
    meaningReversed: 'もう少しで円が結ばれぬ時。最後の一手を惜しまぬよう。完成の手前で立ち止まらず、最後の縁を丁寧に結び終えよう。',
    rarity: 'legendary',
  },

  // === 小アルカナ 杖（Wands・火）数札 01〜10：common ===
  {
    id: 'wands-01',
    numericId: 22,
    name: '杖の一',
    nameEn: 'Ace of Wands',
    suit: 'wands',
    number: 1,
    keywords: ['火種', '衝動', '始動'],
    meaningUpright: '一筋の火が掌に灯る瞬間。創造の衝動が胸の奥から立ち上り、何かを始めたい疼きが満ちる。素直にその熱を、新たな道へと向けよう。',
    meaningReversed: '火が点きそうで点かぬ時。意欲はあれど方向が定まらず燻ぶる。風通しを良くし、心の薪を一本だけでも組み直してみよう。',
    rarity: 'common',
  },
  {
    id: 'wands-02',
    numericId: 23,
    name: '杖の二',
    nameEn: 'Two of Wands',
    suit: 'wands',
    number: 2,
    keywords: ['計画', '展望', '選び'],
    meaningUpright: '高台から地図を広げる時。手元の杖と遠くの杖、二つの世界を見比べ、行くべき方角を冷静に選ぼう。冒険の準備は整っている。',
    meaningReversed: '視野が狭まり、決めかねる時。同じ場所に立ち続けるより、まず一歩外へ出てみよう。景色が変われば、選択肢もまた違って見える。',
    rarity: 'common',
  },
  {
    id: 'wands-03',
    numericId: 24,
    name: '杖の三',
    nameEn: 'Three of Wands',
    suit: 'wands',
    number: 3,
    keywords: ['展開', '待ち', '視野'],
    meaningUpright: '港の岩礁に立ち、帰る船を待つ時。蒔いた種は遠き地で芽吹き、便りが届く前夜にある。視線を広く保ち、機をしずかに待とう。',
    meaningReversed: '待ちが長く、心が痩せる時。期待の方角を見直そう。届かぬ船を恨むより、自ら別の港へ歩み出す勇気を持つ時もある。',
    rarity: 'common',
  },
  {
    id: 'wands-04',
    numericId: 25,
    name: '杖の四',
    nameEn: 'Four of Wands',
    suit: 'wands',
    number: 4,
    keywords: ['祝宴', '安住', '節目'],
    meaningUpright: '四本の柱で祝いの天蓋を立てる時。家路の灯、迎える声、囲む笑顔。節目の喜びを惜しまず分かち合えば、繁栄の根は深く張る。',
    meaningReversed: '表向きの祝いに、隙間の風が吹く時。式の華やかさより、内側の和を整え直そう。土台の小さな歪みを今のうちに直して。',
    rarity: 'common',
  },
  {
    id: 'wands-05',
    numericId: 26,
    name: '杖の五',
    nameEn: 'Five of Wands',
    suit: 'wands',
    number: 5,
    keywords: ['競い', '衝突', '切磋'],
    meaningUpright: '稽古場で杖を交える時。譲らぬ五つの意見が火花を散らす。怒りではなく研鑽として受け止めれば、互いの腕は確かに磨かれてゆく。',
    meaningReversed: '不毛な争いに疲れる時。勝ち負けの場から一度退き、自分の道に戻ろう。譲り合いの一礼で、空気は驚くほど鎮まる。',
    rarity: 'common',
  },
  {
    id: 'wands-06',
    numericId: 27,
    name: '杖の六',
    nameEn: 'Six of Wands',
    suit: 'wands',
    number: 6,
    keywords: ['勝利', '栄誉', '凱旋'],
    meaningUpright: '旗を掲げて街道を行く凱旋の時。歓声は風となり、努めし日々を称える。驕らず、共に走った者へも礼を忘れぬ姿が美しい。',
    meaningReversed: '称賛が静まり、空虚を覚える時。外の評価より、自身が誇れる仕事の手応えを思い出そう。本物の栄誉は、内側に静かに残る。',
    rarity: 'common',
  },
  {
    id: 'wands-07',
    numericId: 28,
    name: '杖の七',
    nameEn: 'Seven of Wands',
    suit: 'wands',
    number: 7,
    keywords: ['防衛', '信念', '抗い'],
    meaningUpright: '高みに立ち、下から伸びる六本を相手取る時。譲れぬ一線を守る勇気が試されている。退かず、しかし傲らず、信念で立ち続けよう。',
    meaningReversed: '防戦に疲れ、足元が崩れそうな時。すべてに応戦せず、本当に大事な一点だけを守ろう。手放してよい矢もきっとある。',
    rarity: 'common',
  },
  {
    id: 'wands-08',
    numericId: 29,
    name: '杖の八',
    nameEn: 'Eight of Wands',
    suit: 'wands',
    number: 8,
    keywords: ['迅速', '知らせ', '急流'],
    meaningUpright: '八本の杖が同じ方向に空を切る時。物事が一気に動き、待ち望んだ便りが舞い込む。流れに遅れぬよう、軽やかな返答を心がけて。',
    meaningReversed: '急ぎが空回りする時。多くの矢が四散し、的を見失う。一度すべてを置き、最初の一本を狙うところから始め直そう。',
    rarity: 'common',
  },
  {
    id: 'wands-09',
    numericId: 30,
    name: '杖の九',
    nameEn: 'Nine of Wands',
    suit: 'wands',
    number: 9,
    keywords: ['粘り', '警戒', '残り火'],
    meaningUpright: '八つの試練を経て、なお九本目の杖を握る時。傷を抱えながらも立ち続ける姿に、最後の門は静かに開く。あと一歩、踏ん張ろう。',
    meaningReversed: '警戒し過ぎて疲弊する時。盾を下ろし、もう敵は去ったと信じてみよう。残り火を消さず、安らぐ場所で休む時も大切である。',
    rarity: 'common',
  },
  {
    id: 'wands-10',
    numericId: 31,
    name: '杖の十',
    nameEn: 'Ten of Wands',
    suit: 'wands',
    number: 10,
    keywords: ['重荷', '責務', '一段落の手前'],
    meaningUpright: '十本の杖を一人で担ぐ時。目的地は近いが、肩は鉛のごとし。何を抱え過ぎているか棚卸しを。手放すことが、ゴールを近づける。',
    meaningReversed: 'ようやく荷を下ろす時。長く背負った義務を一つずつ降ろし、軽くなった肩で空を仰ごう。すべてを背負わずとも、世は廻る。',
    rarity: 'common',
  },

  // === 小アルカナ 杖 コート 11〜14：uncommon ===
  {
    id: 'wands-11',
    numericId: 32,
    name: '杖の小姓',
    nameEn: 'Page of Wands',
    suit: 'wands',
    number: 11,
    keywords: ['好奇心', '知らせ', '若き火'],
    meaningUpright: '火を初めて手にした少年のごとき時。情熱の芽がきらめき、何にでも触れたくなる。失敗を恐れず、まず動いてみるが吉である。',
    meaningReversed: '熱しやすく冷めやすき時。火種を次々と点けては忘れる癖に気づこう。一つの灯を最後まで見守る稽古が、君を大人にする。',
    rarity: 'epic',
  },
  {
    id: 'wands-12',
    numericId: 33,
    name: '杖の騎士',
    nameEn: 'Knight of Wands',
    suit: 'wands',
    number: 12,
    keywords: ['突進', '冒険', '情熱'],
    meaningUpright: '駿馬を駆って炎の道を進む時。恐れより先に体が動き、勢いで運命を切り拓く。後先を案ずる前に、まず走り出す日もある。',
    meaningReversed: '走るほどに道を逸れる時。短気な突進は仲間を置き去りにする。手綱を引き、馬と共に呼吸を整えてから再び駆けよう。',
    rarity: 'epic',
  },
  {
    id: 'wands-13',
    numericId: 34,
    name: '杖の女王',
    nameEn: 'Queen of Wands',
    suit: 'wands',
    number: 13,
    keywords: ['自信', '魅力', '焚火'],
    meaningUpright: '焚火を囲む輪の中心に座すごとき時。温もりと笑みで人を惹き寄せ、揺るがぬ威厳が場を照らす。自らの輝きを惜しまず放とう。',
    meaningReversed: '嫉妬や独占の炎に気をつけて。輝きが翳る時、原因は外ではなく内にある。自信の根を、他者の視線から己の確信へ戻そう。',
    rarity: 'epic',
  },
  {
    id: 'wands-14',
    numericId: 35,
    name: '杖の王',
    nameEn: 'King of Wands',
    suit: 'wands',
    number: 14,
    keywords: ['統率', '構想', '大火'],
    meaningUpright: '大いなる構想を抱き、人を率いる時。情熱は規律で磨かれ、ひとつの国を照らす炎となる。長期の視野で、確かな一手を打とう。',
    meaningReversed: '独裁の炎に注意。強引な指揮は、忠誠を恐怖に変える。耳を澄まし、火を分かち合うことで、王たる威厳は真に輝く。',
    rarity: 'epic',
  },

  // === 小アルカナ 聖杯（Cups・水）数札 01〜10：common ===
  {
    id: 'cups-01',
    numericId: 36,
    name: '聖杯の一',
    nameEn: 'Ace of Cups',
    suit: 'cups',
    number: 1,
    keywords: ['愛', '始まり', '注ぎ'],
    meaningUpright: '天から一筋の水が杯に注がれる時。新たな愛、慈しみ、感受の扉が静かに開く。心を空の器にして、そのきらめきを受け取ろう。',
    meaningReversed: '杯がわずかに傾き、水がこぼれる時。心を閉ざしすぎて、流れ込む慈しみを受けそびれていないか。器を整え直そう。',
    rarity: 'common',
  },
  {
    id: 'cups-02',
    numericId: 37,
    name: '聖杯の二',
    nameEn: 'Two of Cups',
    suit: 'cups',
    number: 2,
    keywords: ['絆', '共鳴', '約束'],
    meaningUpright: '二つの杯を交わし合う時。心と心が同じ波長で揺れ、対等な誓いが結ばれる。利でなく情で結ばれる縁こそ、長く清らかである。',
    meaningReversed: '杯の高さが揃わぬ時。一方が注ぎ、一方が受けるだけでは関係は乾く。互いに目を合わせ、声を交わすところから整え直そう。',
    rarity: 'common',
  },
  {
    id: 'cups-03',
    numericId: 38,
    name: '聖杯の三',
    nameEn: 'Three of Cups',
    suit: 'cups',
    number: 3,
    keywords: ['祝祭', '友情', '共歓'],
    meaningUpright: '三つの杯を高く掲げる時。喜びを分かち合う友が傍にあり、心は満ち、笑いが満つ。今夜は遠慮を脱ぎ、祝いの輪に身を委ねよう。',
    meaningReversed: '祝いの輪が空回りする時。表面の賑わいの陰で、本音が萎んでいないか。少人数の静かな夜に、本当の友と杯を交わそう。',
    rarity: 'common',
  },
  {
    id: 'cups-04',
    numericId: 39,
    name: '聖杯の四',
    nameEn: 'Four of Cups',
    suit: 'cups',
    number: 4,
    keywords: ['倦怠', '内省', '見過ごし'],
    meaningUpright: '三つの杯に飽き、四つ目の差し出された杯に気づかぬ時。今あるものへの感謝を忘れがち。瞼を上げ、足元の贈り物を見直そう。',
    meaningReversed: '倦怠の霧が薄れ始める時。退屈の中にも光は宿ると気づく。差し出された手を、もう一度素直に受け取ってみてもよい。',
    rarity: 'common',
  },
  {
    id: 'cups-05',
    numericId: 40,
    name: '聖杯の五',
    nameEn: 'Five of Cups',
    suit: 'cups',
    number: 5,
    keywords: ['喪失', '嘆き', '残された杯'],
    meaningUpright: '倒れた三つの杯を見つめ涙する時。されど背後にはまだ立っている二つの杯がある。失ったものを悼みつつ、残るものへ視線を戻そう。',
    meaningReversed: '涙が乾き始める時。長く俯いた顔を上げ、まだ手の中にある温もりを確かめよう。喪失の物語に、新しい章が静かに始まる。',
    rarity: 'common',
  },
  {
    id: 'cups-06',
    numericId: 41,
    name: '聖杯の六',
    nameEn: 'Six of Cups',
    suit: 'cups',
    number: 6,
    keywords: ['郷愁', '懐古', '純真'],
    meaningUpright: '幼き日の縁側に座るごとき時。古き友、童心、忘れていた甘やかな記憶が訪れる。過去の優しさを、今に活かす力に変えてゆこう。',
    meaningReversed: '過去に縛られる時。郷愁は美しいが、住む場ではない。古い杯を棚に戻し、今日の杯に新しき水を注ぐ勇気を持とう。',
    rarity: 'common',
  },
  {
    id: 'cups-07',
    numericId: 42,
    name: '聖杯の七',
    nameEn: 'Seven of Cups',
    suit: 'cups',
    number: 7,
    keywords: ['幻惑', '選択', '夢'],
    meaningUpright: '雲の上に七つの杯が浮かぶ時。様々な可能性に目移りし、現実の足元を見失いがち。本当に手に取りたい一杯を、心に問おう。',
    meaningReversed: '霧が晴れ、選ぶ時。実現可能なものと、ただの幻を見分けよう。地に足を戻したあなたなら、最良の一杯を迷わず選べる。',
    rarity: 'common',
  },
  {
    id: 'cups-08',
    numericId: 43,
    name: '聖杯の八',
    nameEn: 'Eight of Cups',
    suit: 'cups',
    number: 8,
    keywords: ['立ち去り', '求道', '月夜'],
    meaningUpright: '八つの杯を背に、月夜の山道へと歩み出す時。満たされぬ何かを求め、慣れ親しんだ場を後にする。その旅は、魂の選びである。',
    meaningReversed: '去るべきか留まるべきか迷う時。荷をまとめかけて手が止まる。焦らず、満月の夜まで決断を待つことを自分に許そう。',
    rarity: 'common',
  },
  {
    id: 'cups-09',
    numericId: 44,
    name: '聖杯の九',
    nameEn: 'Nine of Cups',
    suit: 'cups',
    number: 9,
    keywords: ['満足', '願い成就', '微笑'],
    meaningUpright: '九つの杯を背に、満ちた心で微笑む時。願いがひとつ叶い、温かな満足が体に染みる。今夜は素直に、自身を労ってよい。',
    meaningReversed: '表向きの満足に、心の奥が虚しい時。物の満たしと魂の満たしは別である。本当に欲していたものを、改めて問い直そう。',
    rarity: 'common',
  },
  {
    id: 'cups-10',
    numericId: 45,
    name: '聖杯の十',
    nameEn: 'Ten of Cups',
    suit: 'cups',
    number: 10,
    keywords: ['家族', '円満', '虹'],
    meaningUpright: '十の杯が虹を架けるごとく並ぶ時。家族や仲間との和が極まり、心は穏やかに満ちる。日常の幸を、当たり前にせぬ眼差しを持とう。',
    meaningReversed: '円満を装い、内に冷たい風が吹く時。形だけの和ではなく、本音を交わす夜が必要かもしれない。小さな対話から始めよう。',
    rarity: 'common',
  },

  // === 小アルカナ 聖杯 コート 11〜14：uncommon ===
  {
    id: 'cups-11',
    numericId: 46,
    name: '聖杯の小姓',
    nameEn: 'Page of Cups',
    suit: 'cups',
    number: 11,
    keywords: ['感受', '詩心', '知らせ'],
    meaningUpright: '杯の中から魚が顔を出すごとき時。素直な感性、ふと浮かぶ詩心、夢のような知らせが訪れる。心の柔らかさを大切にしよう。',
    meaningReversed: '感情が幼く揺れる時。気分に振り回されて疲れぬよう、深呼吸を一つ。書き留めた言葉を、明日の自分に読み返させよう。',
    rarity: 'epic',
  },
  {
    id: 'cups-12',
    numericId: 47,
    name: '聖杯の騎士',
    nameEn: 'Knight of Cups',
    suit: 'cups',
    number: 12,
    keywords: ['求愛', '理想', '流麗'],
    meaningUpright: '白馬に杯を捧げ持つ騎士のごとき時。理想を胸に、優美な振る舞いで人の心を動かす。誠の想いは、静かな川のごとく長く流れる。',
    meaningReversed: '理想に酔い、現を見失う時。美辞ばかりが先走ると、約束は薄まる。次の一歩を、地に足の付いた言葉で語り直そう。',
    rarity: 'epic',
  },
  {
    id: 'cups-13',
    numericId: 48,
    name: '聖杯の女王',
    nameEn: 'Queen of Cups',
    suit: 'cups',
    number: 13,
    keywords: ['共感', '直観', '静水'],
    meaningUpright: '静かな湖畔に座する女王のごとき時。深い共感力で他者の痛みを受け止め、静かな智慧で癒しを与える。あなた自身もまた水に映ろう。',
    meaningReversed: '共感しすぎ、自他の境が滲む時。他者の波に飲まれぬよう、岸辺へ戻ろう。優しさは、まず自身の杯を満たしてからである。',
    rarity: 'epic',
  },
  {
    id: 'cups-14',
    numericId: 49,
    name: '聖杯の王',
    nameEn: 'King of Cups',
    suit: 'cups',
    number: 14,
    keywords: ['包容', '沈着', '大海'],
    meaningUpright: '荒波の上にあっても、心は深海のごとく静かなる時。感情を統べる王として、周囲に安心を分け与える。大いなる包容が場を整える。',
    meaningReversed: '内なる嵐を押し隠す時。沈着の仮面の下で、感情が荒れていないか。信ずる者に胸の内を打ち明けることもまた、王の徳である。',
    rarity: 'epic',
  },

  // === 小アルカナ 剣（Swords・風）数札 01〜10：common ===
  {
    id: 'swords-01',
    numericId: 50,
    name: '剣の一',
    nameEn: 'Ace of Swords',
    suit: 'swords',
    number: 1,
    keywords: ['真実', '鋭さ', '突破'],
    meaningUpright: '雲間より一振りの剣が顕れる時。混迷を断ち切る明晰な思考が降りてくる。真実を恐れず、必要な一刀を心静かに振るおう。',
    meaningReversed: '鋭さが空を切る時。理屈が独り歩きし、現実を傷つけぬよう注意。剣を一度鞘に納め、感情にも耳を傾けてから抜こう。',
    rarity: 'common',
  },
  {
    id: 'swords-02',
    numericId: 51,
    name: '剣の二',
    nameEn: 'Two of Swords',
    suit: 'swords',
    number: 2,
    keywords: ['拮抗', '保留', '目隠し'],
    meaningUpright: '二振りの剣を胸の前で交えたまま、目を布で覆う時。決められぬ膠着の中、敢えて見ない選びもある。心の声を静かに聴こう。',
    meaningReversed: '目隠しが解け始める時。見たくなかった真実が静かに現れる。怖れず受け止めれば、長く膠着していた状況は動き出す。',
    rarity: 'common',
  },
  {
    id: 'swords-03',
    numericId: 52,
    name: '剣の三',
    nameEn: 'Three of Swords',
    suit: 'swords',
    number: 3,
    keywords: ['痛み', '別れ', '雨'],
    meaningUpright: '雨に濡れた心臓に三振りの剣が刺さる時。深い悲しみを否定せず、まず泣くことを許そう。痛みは、いずれ静かな雨上がりへ。',
    meaningReversed: '雨が止みかける時。長く流した涙の意味を、ようやく整理できる頃合い。剣を一本ずつ抜き、傷口を空気に晒して癒そう。',
    rarity: 'common',
  },
  {
    id: 'swords-04',
    numericId: 53,
    name: '剣の四',
    nameEn: 'Four of Swords',
    suit: 'swords',
    number: 4,
    keywords: ['休息', '沈黙', '回復'],
    meaningUpright: '静かな堂の中で剣を傍らに横たわる時。戦の合間に魂を休める必要がある。眠り、祈り、沈黙の中で力が静かに戻ってくる。',
    meaningReversed: '長すぎる休息に身体が鈍る時。そろそろ起き上がり、ゆっくりと体を伸ばそう。微かな動きから、再び日常の流れに戻ってゆく。',
    rarity: 'common',
  },
  {
    id: 'swords-05',
    numericId: 54,
    name: '剣の五',
    nameEn: 'Five of Swords',
    suit: 'swords',
    number: 5,
    keywords: ['争い', '勝者の虚しさ', '自省'],
    meaningUpright: '三振りを拾い、二人の背に剣を見送る時。勝ったはずなのに胸に風が吹く。勝敗より、何を守るための戦かを問い直そう。',
    meaningReversed: '争いの煙が薄れる時。先に頭を下げる勇気を持てば、関係は意外と早く修復される。プライドより、繋がりを選ぼう。',
    rarity: 'common',
  },
  {
    id: 'swords-06',
    numericId: 55,
    name: '剣の六',
    nameEn: 'Six of Swords',
    suit: 'swords',
    number: 6,
    keywords: ['移行', '渡し舟', '静かな旅'],
    meaningUpright: '六振りの剣を舟に積み、静かな川を渡る時。痛みを抱えたまま、それでも別の岸へ向かう旅。波立てず、静かに進んでゆこう。',
    meaningReversed: '過去の岸に未練が残る時。一度振り返るのは構わぬが、再び舳先を前へ。流れに身を委ねれば、彼岸は近づいてくる。',
    rarity: 'common',
  },
  {
    id: 'swords-07',
    numericId: 56,
    name: '剣の七',
    nameEn: 'Seven of Swords',
    suit: 'swords',
    number: 7,
    keywords: ['策略', '隠匿', '機転'],
    meaningUpright: '七振りのうち五振りを抱え、こっそり立ち去る時。正面突破より迂回の智慧が必要な場面。ただし誠実さの一線は守ろう。',
    meaningReversed: '隠していた何かが明るみへ出る時。今のうちに自ら明かしてしまえば、傷は浅い。誠実さは、結局のところ最強の策である。',
    rarity: 'common',
  },
  {
    id: 'swords-08',
    numericId: 57,
    name: '剣の八',
    nameEn: 'Eight of Swords',
    suit: 'swords',
    number: 8,
    keywords: ['制限', '自縛', '視界'],
    meaningUpright: '八振りに囲まれ、目隠しで立ち尽くす時。されど縄は意外と緩く、扉も近い。思い込みの檻に気づけば、足は自由に動き出す。',
    meaningReversed: '縄が解け、目隠しが落ちる時。長く自分を縛っていた信念に終止符を打とう。最初の一歩はぎこちなくとも、必ず歩める。',
    rarity: 'common',
  },
  {
    id: 'swords-09',
    numericId: 58,
    name: '剣の九',
    nameEn: 'Nine of Swords',
    suit: 'swords',
    number: 9,
    keywords: ['不安', '夜の懊悩', '過剰心配'],
    meaningUpright: '夜更けに九振りの剣の影に怯える時。心配の多くは、実際よりも大きく見える。灯を点け、書き出し、独りで抱え込まぬように。',
    meaningReversed: '夜明けが近づく時。長い悪夢の正体を見極めれば、案外小さき影に過ぎぬとわかる。誰かに話してしまえば、嘘のように軽くなる。',
    rarity: 'common',
  },
  {
    id: 'swords-10',
    numericId: 59,
    name: '剣の十',
    nameEn: 'Ten of Swords',
    suit: 'swords',
    number: 10,
    keywords: ['終わり', '底打ち', '黎明'],
    meaningUpright: '十振りの剣が背に刺さり倒れ伏す時。されど見上げれば地平に朝焼けが滲む。これ以上下はないと知る今こそ、再生の入口である。',
    meaningReversed: 'ようやく身を起こす時。傷は深かれど、立ち上がる力は確かに戻ってくる。何度でも夜明けは訪れる、と自分に告げて。',
    rarity: 'common',
  },

  // === 小アルカナ 剣 コート 11〜14：uncommon ===
  {
    id: 'swords-11',
    numericId: 60,
    name: '剣の小姓',
    nameEn: 'Page of Swords',
    suit: 'swords',
    number: 11,
    keywords: ['探求', '機敏', '風読み'],
    meaningUpright: '風の便りを耳に、剣を構える少年のごとき時。好奇と警戒を併せ持ち、機敏に情報を集める。学ぶ姿勢が、今のあなたの武器である。',
    meaningReversed: '言葉が早足になり、人を傷つける時。鋭さは美徳だが、抜き身は危うい。一呼吸置いてから、言葉という剣を放とう。',
    rarity: 'epic',
  },
  {
    id: 'swords-12',
    numericId: 61,
    name: '剣の騎士',
    nameEn: 'Knight of Swords',
    suit: 'swords',
    number: 12,
    keywords: ['突撃', '弁舌', '急進'],
    meaningUpright: '風を切り裂いて駆ける騎士のごとき時。明晰な判断と素早い行動で道を切り拓く。ただし馬を疲れさせぬよう、緩急を忘れずに。',
    meaningReversed: '突進が空回り、敵を増やす時。論破より対話を、勝利より着地を選ぼう。一度馬を降り、相手の旗を改めて見つめる時間を持って。',
    rarity: 'epic',
  },
  {
    id: 'swords-13',
    numericId: 62,
    name: '剣の女王',
    nameEn: 'Queen of Swords',
    suit: 'swords',
    number: 13,
    keywords: ['明晰', '自立', '凛'],
    meaningUpright: '玉座の上で剣を真直ぐ立てる女王の時。情に流されず、しかし冷たくもない、澄んだ判断がある。経験が智慧へと結晶している。',
    meaningReversed: '鋭さが冷たさに偏る時。守るための刃が、いつの間にか身近な者を傷つけていないか。柔らかな言葉を一つ、思い出してみよう。',
    rarity: 'epic',
  },
  {
    id: 'swords-14',
    numericId: 63,
    name: '剣の王',
    nameEn: 'King of Swords',
    suit: 'swords',
    number: 14,
    keywords: ['理性', '統治', '真理'],
    meaningUpright: '揺るがぬ理性で国を統べる王の時。事実を見極め、感情に振り回されず、公正な裁きを下す。誠実な言葉は、最も鋭き剣となる。',
    meaningReversed: '理屈が独裁となる時。正論は人を黙らせるが、納得はさせぬ。理を説く前に、相手の事情にも耳を傾ける王であってほしい。',
    rarity: 'epic',
  },

  // === 小アルカナ 金貨（Pentacles・地）数札 01〜10：common ===
  {
    id: 'pentacles-01',
    numericId: 64,
    name: '金貨の一',
    nameEn: 'Ace of Pentacles',
    suit: 'pentacles',
    number: 1,
    keywords: ['機会', '種', '礎'],
    meaningUpright: '開いた手の上に一枚の金貨が静かに置かれる時。確かな物質的機会の到来。地に足を付け、種を蒔けば、ゆっくり確実に実りへ向かう。',
    meaningReversed: '機を逃しかける時。慎重さも度を越せば停滞となる。差し出された一枚を、まず受け取って、それから吟味してみよう。',
    rarity: 'common',
  },
  {
    id: 'pentacles-02',
    numericId: 65,
    name: '金貨の二',
    nameEn: 'Two of Pentacles',
    suit: 'pentacles',
    number: 2,
    keywords: ['均衡', '軽妙', '双葉'],
    meaningUpright: '二枚の金貨を軽やかに手玉に取る時。仕事と暮らし、収入と支出、二つの天秤を笑いつつ釣り合わせる。柔らかな足取りが鍵となる。',
    meaningReversed: '手玉が落ちそうな時。同時に追える数を超えていないか。優先順位を一つだけ決め、他は今は脇に置いてもよい。',
    rarity: 'common',
  },
  {
    id: 'pentacles-03',
    numericId: 66,
    name: '金貨の三',
    nameEn: 'Three of Pentacles',
    suit: 'pentacles',
    number: 3,
    keywords: ['協働', '技', '大工'],
    meaningUpright: '三人の職人が堂宇の梁を組む時。各々の技と知恵を持ち寄り、ひとつの仕事を仕上げる喜び。互いの腕への敬意が、最高の建材となる。',
    meaningReversed: '連携に隙間風が吹く時。役割や報酬の不明瞭が綻びを呼ぶ。一度全員で円座を組み、初めから手順を確かめ直そう。',
    rarity: 'common',
  },
  {
    id: 'pentacles-04',
    numericId: 67,
    name: '金貨の四',
    nameEn: 'Four of Pentacles',
    suit: 'pentacles',
    number: 4,
    keywords: ['守銭', '執着', '抱え'],
    meaningUpright: '四枚の金貨を胸に抱え、放さぬ時。安心の鎧は時に呼吸を浅くする。守ることと貯めることの違いを、静かに見直してみよう。',
    meaningReversed: '握っていた手を緩める時。少しの寛容、少しの分かち合いが、巡り巡って大きな豊かさを連れて戻ってくる。',
    rarity: 'common',
  },
  {
    id: 'pentacles-05',
    numericId: 68,
    name: '金貨の五',
    nameEn: 'Five of Pentacles',
    suit: 'pentacles',
    number: 5,
    keywords: ['困窮', '寒夜', '寄り添い'],
    meaningUpright: '雪の夜、灯の点る堂の前を通り過ぎる時。困窮の中にあっても、見上げれば扉は開かれている。助けを乞う声を恥じる必要はない。',
    meaningReversed: '寒さの底を抜ける時。長き欠乏に終わりが見え、温かき場所が再び見つかる。受け取ることを、自分に許そう。',
    rarity: 'common',
  },
  {
    id: 'pentacles-06',
    numericId: 69,
    name: '金貨の六',
    nameEn: 'Six of Pentacles',
    suit: 'pentacles',
    number: 6,
    keywords: ['施し', '公正', '循環'],
    meaningUpright: '天秤を手に、与え合う者と受け取る者がある時。施しは上下ではなく、循環の風である。受けるも与えるも、心を澄ませて。',
    meaningReversed: '与え方や受け方の歪みに注意。負い目を生まぬ施しを、見返りを期待せぬ姿勢で。無理な負担を断る勇気も時に必要。',
    rarity: 'common',
  },
  {
    id: 'pentacles-07',
    numericId: 70,
    name: '金貨の七',
    nameEn: 'Seven of Pentacles',
    suit: 'pentacles',
    number: 7,
    keywords: ['忍耐', '結実', '見守り'],
    meaningUpright: '七つの実りを前に、汗を拭いて立つ農夫の時。育てたものの成熟を、焦らず見守る局面。今はまだ収穫ではなく、観察の季節である。',
    meaningReversed: '待ちに耐えかね、青いまま摘もうとする時。あと少しだけ、土と苗を信じてみよう。早すぎる手出しは、味を損なうことがある。',
    rarity: 'common',
  },
  {
    id: 'pentacles-08',
    numericId: 71,
    name: '金貨の八',
    nameEn: 'Eight of Pentacles',
    suit: 'pentacles',
    number: 8,
    keywords: ['鍛錬', '没頭', '職人'],
    meaningUpright: '工房にて八つ目の金貨を黙々と打つ時。地味で繰り返しの作業こそが、確かな腕を作る。今日の一打が、明日の名工へ続く道である。',
    meaningReversed: '手仕事が惰性に流れる時。手を止めて、なぜ作っているのかを思い出そう。心を込め直せば、同じ作業も再び輝き始める。',
    rarity: 'common',
  },
  {
    id: 'pentacles-09',
    numericId: 72,
    name: '金貨の九',
    nameEn: 'Nine of Pentacles',
    suit: 'pentacles',
    number: 9,
    keywords: ['自立', '余裕', '庭'],
    meaningUpright: '自らの庭で九つの実りに囲まれる時。長年の努めが、品ある豊かさとして結実している。独りの時間も、確かな贅沢である。',
    meaningReversed: '余裕の陰に孤独が滲む時。豊かさを共に味わう誰かを、庭へ招いてもよい。自立は、繋がりを拒むことではない。',
    rarity: 'common',
  },
  {
    id: 'pentacles-10',
    numericId: 73,
    name: '金貨の十',
    nameEn: 'Ten of Pentacles',
    suit: 'pentacles',
    number: 10,
    keywords: ['継承', '家', '安泰'],
    meaningUpright: '大家族のごとく十枚の金貨が連なる時。築き上げた基盤が世代を超えて伝わる豊かさ。今ここで得たものを、次に渡す視点を持とう。',
    meaningReversed: '受け継ぐものと、自ら築くものの境界に迷う時。形ばかりの相続より、心の遺産を見極めよう。自分の番にふさわしい育み方を。',
    rarity: 'common',
  },

  // === 小アルカナ 金貨 コート 11〜14：uncommon ===
  {
    id: 'pentacles-11',
    numericId: 74,
    name: '金貨の小姓',
    nameEn: 'Page of Pentacles',
    suit: 'pentacles',
    number: 11,
    keywords: ['学び', '真面目', '種蒔き'],
    meaningUpright: '一枚の金貨をじっと見つめる学徒のごとき時。新たな技や知識への憧れが芽吹く。地道に積み上げる姿勢が、いずれ大樹に育ってゆく。',
    meaningReversed: '学びが頭でっかちになる時。机から離れ、実際に手を動かしてみよう。土に触れた知恵だけが、本当に身につく。',
    rarity: 'epic',
  },
  {
    id: 'pentacles-12',
    numericId: 75,
    name: '金貨の騎士',
    nameEn: 'Knight of Pentacles',
    suit: 'pentacles',
    number: 12,
    keywords: ['着実', '忍耐', '田畑'],
    meaningUpright: '黒馬に乗り、田畑を見回る騎士のごとき時。派手さはないが、揺るぎなく着実な歩み。退屈に見える日々こそが、最も豊かな実りを生む。',
    meaningReversed: '着実が頑迷へと固まる時。同じ手順に固執せず、たまには別の畝の作り方を試してみよう。柔らかさは退化ではない。',
    rarity: 'epic',
  },
  {
    id: 'pentacles-13',
    numericId: 76,
    name: '金貨の女王',
    nameEn: 'Queen of Pentacles',
    suit: 'pentacles',
    number: 13,
    keywords: ['育み', '豊穣', '包擁'],
    meaningUpright: '緑深き庭の中央に座する女王のごとき時。身近な命を慈しみ、暮らしを丁寧に整える力に長ける。地に根ざした優しさが場を満たす。',
    meaningReversed: '世話を焼きすぎ、自分が痩せる時。庭の主はまず自身を養う。湯を沸かし、好きな菓子を一つ、自分のために選んでみよう。',
    rarity: 'epic',
  },
  {
    id: 'pentacles-14',
    numericId: 77,
    name: '金貨の王',
    nameEn: 'King of Pentacles',
    suit: 'pentacles',
    number: 14,
    keywords: ['安泰', '実業', '豊穣'],
    meaningUpright: '黄金の玉座に着き、領地の豊かさを見渡す王の時。長年の堅実が形となり、人と財を統べる安らぎを持つ。寛大さもまた、王の徳。',
    meaningReversed: '富に縛られ、新しき風を拒む時。鎧の重さを点検しよう。本当の安泰は、抱え込みではなく、惜しみなく分かち合う流れの中にある。',
    rarity: 'epic',
  },
]
